# Generated by Django 6.0.2 on 2026-02-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospotifydownloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifylink',
            name='songs',
            field=models.JSONField(default=list),
        ),
    ]
